export const EXCHANGE_RATES = {
  "EUR/USD": 1.085,
  "GBP/USD": 1.265,
  "USD/JPY": 149.5,
  "USD/CHF": 0.875,
  "AUD/USD": 0.658,
  "USD/CAD": 1.365,
  "NZD/USD": 0.612,
  "EUR/GBP": 0.858,
  "EUR/JPY": 162.15,
  "GBP/JPY": 189.05,
}

export const CURRENCY_OPTIONS = [
  { value: "USD", label: "USD" },
  // { value: "EUR", label: "EUR" },
  // { value: "GBP", label: "GBP" },
  // { value: "JPY", label: "JPY" },
  // { value: "CAD", label: "CAD" },
  // { value: "AUD", label: "AUD" },
  // { value: "CHF", label: "CHF" },
]

export const CURRENCY_PAIR_OPTIONS = [
  { value: "XAUUSD", label: "XAU/USD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "USOIL", label: "USOIL/USD", base: "USOIL", quote: "USD", broker: "fxcm" },
  { value: "BTCUSD", label: "BTC/USD", base: "BTC", quote: "USD", broker: "coinbase" },
  { value: "NZDUSD", label: "NZD/USD", base: "NZD", quote: "USD", broker: "fxcm" },
  { value: "AUDUSD", label: "AUD/USD", base: "AUD", quote: "USD", broker: "fxcm" },
  { value: "USDJPY", label: "USD/JPY", base: "USD", quote: "JPY", broker: "fxcm" },
  { value: "USDCHF", label: "USD/CHF", base: "USD", quote: "CHF", broker: "fxcm" },
  { value: "EURUSD", label: "EUR/USD", base: "EUR", quote: "USD", broker: "fxcm" },
  { value: "GBPUSD", label: "GBP/USD", base: "GBP", quote: "USD", broker: "fxcm" },
  { value: "USDCAD", label: "USD/CAD", base: "USD", quote: "CAD", broker: "fxcm" },
  { value: "AUDNZD", label: "AUD/NZD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "AUDJPY", label: "AUD/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "AUDCHF", label: "AUD/CHF", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURAUD", label: "EUR/AUD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "GBPAUD", label: "GBP/AUD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "AUDCAD", label: "AUD/CAD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "NZDJPY", label: "NZD/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "NZDCHF", label: "NZD/CHF", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURNZD", label: "EUR/NZD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "GBPNZD", label: "GBP/NZD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "NZDCAD", label: "NZD/CAD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "CHFJPY", label: "CHF/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURJPY", label: "EUR/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "GBPJPY", label: "GBP/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "CADJPY", label: "CAD/JPY", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURCHF", label: "EUR/CHF", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "GBPCHF", label: "GBP/CHF", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "CADCHF", label: "CAD/CHF", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURGBP", label: "EUR/GBP", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "EURCAD", label: "EUR/CAD", base: "XAU", quote: "USD", broker: "fxcm" },
  { value: "GBPCAD", label: "GBP/CAD", base: "XAU", quote: "USD", broker: "fxcm" },
]

export const RISK_MANAGEMENT_TIPS = [
  "Never risk more than 1-2% per trade",
  "Maintain minimum 1:2 risk-reward ratio",
  "Use proper stop losses on every trade",
  "Diversify across multiple currency pairs",
  "Keep a trading journal to track performance",
]
